### ISSUE TITLE
Add support for URLs

### ISSUE THREAD

**Issue by hbcondo** [balbarak/WeasyPrint-netcore#2]
WeasyPrint can produce PDFs from data URIs. Could the `GeneratePDF` method be updated to support this feature? Thanks.

Reference: https://weasyprint.readthedocs.io/en/latest/features.html#urls

**Comment by balbarak** [comment]
We will add this feature in the next release and update to the latest version of weasyprint

Thanks

**Comment by balbarak** [comment]
The feature is already added. The issue will be closed

Thanks
