### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by aditya119** [balbarak/WeasyPrint-netcore#5]
Hey! I'm getting
`"Message":"An error has occurred.","ExceptionMessage":"Access to the path 'C:\\WINDOWS\\SysWOW64\\inetsrv\\weasyprint-v48' is denied.","ExceptionType":"System.UnauthorizedAccessException"`
when trying to generate pdf from HTML text.

**Comment by balbarak** [comment]
Hello,

The plugin needs to create folders on project path. Are you putting your solutions in Syswowo64 ?

try to use any place that the project can write files on disk

Thanks

**Comment by VincentRochet** [comment]
I want into that issue also, this is particularly annoying when deploying in prod environments, as tha user running the service is not supposed to have write access in the folder.
What about a fallback to TEMP ?

**Comment by balbarak** [comment]
Now all files are created in AppData

Thank you for your suggestions
